# Per-tool implementation source lists for the compiler.
#
# Add dev/src/foo.cpp to the tools that use it by adding `foo` below. For
# subdirectories, use the path without `.cpp`, such as `parser/foo`.

FRONTEND_SOURCE_SET_TARGETS := abimangle pptoken posttoken ctrlexpr macro preproc recog nsdecl nsinit cy86 cppgm++ lowiropt lowir2cy86 lowir2native

FRONTEND_OBJ_BASENAMES_abimangle := abi_mangle_model abi_mangle_parse abi_mangle
FRONTEND_OBJ_BASENAMES_pptoken := pp_tokenizer
FRONTEND_OBJ_BASENAMES_posttoken := pp_tokenizer post_tokenizer
FRONTEND_OBJ_BASENAMES_ctrlexpr := pp_tokenizer post_tokenizer control_expression
FRONTEND_OBJ_BASENAMES_macro := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor
FRONTEND_OBJ_BASENAMES_preproc := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor
FRONTEND_OBJ_BASENAMES_recog := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor pa6_recognizer
FRONTEND_OBJ_BASENAMES_nsdecl := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor pa7_semantic
FRONTEND_OBJ_BASENAMES_nsinit := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor pa8_model pa8_parser pa8_semantic
FRONTEND_OBJ_BASENAMES_cy86 := pp_tokenizer post_tokenizer control_expression hosted_builtin_registry hosted_preprocessor_probes macro_operator_code macro_processor cy86_frontend cy86_backend cy86_program
FRONTEND_OBJ_BASENAMES_cppgm++ := pp_tokenizer post_tokenizer control_expression hosted_preprocessor_probes macro_operator_code macro_processor preprocessor frontend_intern hosted_builtin_registry hosted_extension_registry pa10_syntax_model pa10_brace_matching pa32_object_attribute_syntax pa10_syntax pa10_syntax_driver pa10_syntax_stats pa11_model pa11_type_layout pa11_inheritance_model pa11_semantic hosted_extension_semantic pa12_semantic pa12_semantic_capacity pa12_semantic_driver pa12_semantic_calls pa12_semantic_constructor_elision pa12_semantic_declarations pa32_object_data_semantic pa33_abi_tag_semantic pa32_template_preemption_semantic pa12_semantic_declarator_types hosted_builtin_semantic pa34_hosted_trait_semantic pa12_semantic_conversion_functions pa12_semantic_function_declarations pa12_semantic_inheritance pa12_semantic_initialization pa12_semantic_list_initialization pa12_semantic_literals pa12_semantic_operators pa12_semantic_render pa12_semantic_scope pa12_semantic_special_members pa12_semantic_storage pa12_semantic_tables pa30_region_semantic pa28_virtual_base_model pa28_virtual_base_semantic pa28_polymorphism_semantic pa25_lambda_capture_semantic pa25_range_for_semantic pa26_exception_semantic pa26_initializer_list_semantic pa26_rtti_semantic pa27_base_path_model pa27_multibase_semantic pa27_member_pointer_semantic pa19_template_syntax_identity pa19_template_semantic pa19_template_validation pa19_function_template_deduction pa19_function_template_instantiation pa19_semantic_ambiguity pa20_constant_semantic pa20_template_semantic pa20_pack_semantic pa21_constant_evaluator pa21_object_evaluator pa21_address_evaluator pa21_local_static_semantic pa22_template_semantic pa22_friend_semantic pa23_nondeduced_semantic pa23_result_identity pa32_function_template_abi_result pa23_placeholder_semantic pa24_template_integration pa17_constructor_definition_semantic pa18_polymorphism_semantic abi_mangle_model abi_mangle pa15_lowir_model pa15_lowering pa15_lowering_abi pa15_lowering_driver pa15_lowering_support pa15_source_type_lowering pa15_lowir_render pa16_static_initializer_lowering pa16_operator_resolution pa18_polymorphism_lowering pa28_polymorphism_lowering pa30_lowir_adapter pa30_object pa30_elf_object lowir_parse lowir_prepare lowir_serialize lowir_inline_o1 lowir_opt lowir_force_inline lowir_native_abi lowir_native_analysis lowir_native_code_buffer lowir_native_eh lowir_native_float_bits lowir_native_host_eh lowir_native_mir lowir_native_object_elf lowir_native_opt lowir_native_program lowir_native_registers lowir_native_selection lowir_native_session lowir_native_stack lowir_native_varargs lowir_native_wide lowir_native lowir_native_elf mir_model
FRONTEND_OBJ_BASENAMES_cppgm++ += lowir_native_data_layout
FRONTEND_OBJ_BASENAMES_cppgm++ += lowir_native_control_flow
FRONTEND_OBJ_BASENAMES_cppgm++ += pa32_entity_ownership_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa15_force_inline
FRONTEND_OBJ_BASENAMES_cppgm++ += pa19_internal_identity_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa19_template_partial_storage
FRONTEND_OBJ_BASENAMES_cppgm++ += pa21_static_constant_storage
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_layout_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_gnu_asm_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_numeric_type_model
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_numeric_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_numeric_template_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_complex_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_pack_builtin_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_aggregate_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_compiler_builtin_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_control_flow_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_wide_constant_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa34_source_identity
FRONTEND_OBJ_BASENAMES_cppgm++ += pa19_template_shape_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa12_condition_semantic
FRONTEND_OBJ_BASENAMES_cppgm++ += pa11_name_identity
FRONTEND_OBJ_BASENAMES_cppgm++ += pa12_semantic_class_layout
FRONTEND_OBJ_BASENAMES_cppgm++ += pa12_semantic_constructor_demand
FRONTEND_OBJ_BASENAMES_lowiropt := lowir_parse lowir_prepare lowir_serialize lowir_inline_o1 lowir_opt
FRONTEND_OBJ_BASENAMES_lowir2cy86 := lowir_parse lowir_prepare lowir_cy86
FRONTEND_OBJ_BASENAMES_lowir2native := lowir_parse lowir_prepare lowir_force_inline mir_model lowir_native_abi lowir_native_analysis lowir_native_code_buffer lowir_native_eh lowir_native_float_bits lowir_native_host_eh lowir_native_mir lowir_native_object_elf lowir_native_opt lowir_native_program lowir_native_registers lowir_native_selection lowir_native_session lowir_native_stack lowir_native_varargs lowir_native_wide lowir_native lowir_native_elf
FRONTEND_OBJ_BASENAMES_lowir2native += lowir_native_data_layout
FRONTEND_OBJ_BASENAMES_lowir2native += lowir_native_control_flow
