# Per-tool implementation source lists for the compiler.
#
# Add dev/src/foo.cpp to the responsibility list that owns it. For
# subdirectories, use the path without `.cpp`, such as `syntax/parser/foo`.
# Compose responsibility groups as `FRONTEND_SOURCE_IDS_*`; the
# `FRONTEND_OBJ_BASENAMES_<tool>` variables remain the per-tool interface.
# Keep the composed target order stable: it is also the canonical link order.

FRONTEND_SOURCE_SET_TARGETS := abimangle pptoken posttoken ctrlexpr macro preproc recog nsdecl nsinit cy86 cppgm++ lowiropt lowir2cy86 lowir2native
FRONTEND_TEST_RUNNER_SOURCE_ID := support/testing/test_runner
FRONTEND_BUILTIN_CONFIG_SOURCE_ID := preprocess/preprocessor

FRONTEND_SOURCE_IDS_PREPROCESS_TOKEN := preprocess/tokens/pp_tokenizer
FRONTEND_SOURCE_IDS_PREPROCESS_POSTTOKEN := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOKEN) preprocess/tokens/post_tokenizer
FRONTEND_SOURCE_IDS_PREPROCESS_CONTROL := $(FRONTEND_SOURCE_IDS_PREPROCESS_POSTTOKEN) preprocess/expressions/control_expression
FRONTEND_SOURCE_IDS_PREPROCESS_MACRO := $(FRONTEND_SOURCE_IDS_PREPROCESS_CONTROL) preprocess/hosted/builtin_registry preprocess/hosted/preprocessor_probes preprocess/macros/macro_operator_code preprocess/macros/macro_processor
FRONTEND_SOURCE_IDS_PREPROCESS_TOOL := $(FRONTEND_SOURCE_IDS_PREPROCESS_MACRO) preprocess/tool_support

FRONTEND_SOURCE_IDS_ABI_MANGLE_TOOL := abi/itanium/abi_mangle_model abi/itanium/abi_mangle_parse abi/itanium/abi_mangle_identity abi/itanium/abi_mangle_graph_argument abi/itanium/abi_mangle_graph_type abi/itanium/abi_mangle_type_vocabulary abi/itanium/abi_mangle_presentation abi/itanium/abi_mangle_substitution abi/itanium/abi_mangle

FRONTEND_SOURCE_IDS_RECOGNITION := recognition/recognizer
FRONTEND_SOURCE_IDS_NAMESPACE_SEMANTIC := namespace_semantics/analysis
FRONTEND_SOURCE_IDS_NAMESPACE_INITIALIZATION := namespace_initialization/model namespace_initialization/parser namespace_initialization/driver
FRONTEND_SOURCE_IDS_CY86 := cy86/cy86_frontend cy86/cy86_backend cy86/cy86_program

FRONTEND_SOURCE_IDS_CPPGM_PREPROCESS := preprocess/tokens/pp_tokenizer preprocess/tokens/post_tokenizer preprocess/expressions/control_expression preprocess/hosted/preprocessor_probes preprocess/macros/macro_operator_code preprocess/macros/macro_processor preprocess/preprocessor support/interning/frontend_intern preprocess/hosted/builtin_registry hosted_extension_registry
FRONTEND_SOURCE_IDS_CPPGM_SYNTAX_PRIMARY := syntax/model/arena syntax/parser/brace_matching syntax/extensions/object_attributes syntax/parser/parser syntax/driver syntax/stats
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_PRIMARY := semantic/model/program semantic/object_model/type_layout semantic/object_model/inheritance semantic/extensions/hosted_extensions semantic/analysis/analyzer semantic/analysis/name_resolution semantic/analysis/capacity semantic/driver semantic/expressions/calls semantic/lifetime/elision semantic/declarations/analysis semantic/object_model/object_data semantic/extensions/abi_tags semantic/templates/preemption semantic/declarations/declarator_types semantic/extensions/hosted_builtins semantic/extensions/hosted_traits semantic/expressions/conversion_functions semantic/declarations/functions semantic/object_model/inheritance_analysis semantic/initialization/analysis semantic/initialization/list_initialization semantic/expressions/literals semantic/expressions/operators semantic/presentation/render semantic/analysis/scope semantic/lifetime/special_members semantic/analysis/storage semantic/analysis/index_tables semantic/extensions/regions semantic/object_model/virtual_base_model semantic/object_model/virtual_bases semantic/object_model/polymorphic_layout semantic/extensions/lambda_capture semantic/extensions/range_for semantic/extensions/exceptions semantic/initialization/initializer_lists semantic/object_model/rtti semantic/object_model/base_paths semantic/object_model/multiple_inheritance semantic/expressions/member_pointers semantic/templates/syntax_identity semantic/presentation/templates semantic/templates/classes semantic/templates/validation semantic/templates/function_deduction semantic/templates/function_instantiation semantic/templates/ambiguities semantic/constants/analysis semantic/templates/arguments semantic/templates/packs semantic/constants/scalar_evaluator semantic/constants/object_evaluator semantic/constants/address_evaluator semantic/lifetime/local_statics semantic/templates/aliases_and_lambdas semantic/declarations/friends semantic/templates/nondeduced_contexts semantic/templates/result_identity semantic/templates/function_abi_result semantic/templates/placeholders semantic/templates/integration semantic/lifetime/constructor_definitions semantic/object_model/polymorphism
FRONTEND_SOURCE_IDS_CPPGM_ABI := abi/itanium/abi_mangle_model abi/itanium/abi_mangle_identity abi/itanium/abi_mangle_graph_argument abi/itanium/abi_mangle_graph_type abi/itanium/abi_mangle_type_vocabulary abi/itanium/abi_mangle_presentation abi/itanium/abi_mangle_substitution abi/itanium/abi_mangle
FRONTEND_SOURCE_IDS_CPPGM_LOWERING_PRIMARY_BEFORE_OVERLOAD := lowering/ir/model lowering/core/program_lowerer lowering/abi/symbol_metadata lowering/abi/emission_policy lowering/abi/mangling lowering/core/driver lowering/support/identity_maps lowering/abi/symbol_names lowering/core/source_types lowering/ir/render lowering/objects/storage_facts lowering/objects/static_initialization
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_OVERLOAD := semantic/expressions/overload_resolution
FRONTEND_SOURCE_IDS_CPPGM_LOWERING_PRIMARY_AFTER_OVERLOAD := lowering/objects/polymorphism lowering/objects/vtable_thunks lowir/io/frontend_adapter compiler_object/serialization compiler_object/linker compiler_object/elf_import
FRONTEND_SOURCE_IDS_CPPGM_LOWIR_NATIVE_PRIMARY := lowir/io/parse lowir/io/prepare lowir/io/serialize lowir/analysis/inline lowir/optimize/inline_o1 lowir/optimize/pipeline lowir/optimize/force_inline native/errors native/lowering/abi native/analysis/function native/mir/block_labels native/object/code_buffer native/eh/lowering native/allocation/frame_forwarding native/eh/host_regions native/mir/construction native/object/elf_format native/mir/optimize native/driver/program native/allocation/registers native/lowering/selection native/driver/session native/frame/stack native/lowering/varargs native/lowering/wide native/lowering/function native/object/elf_writer native/mir/model
FRONTEND_SOURCE_IDS_CPPGM_NATIVE_EXTENSION := native/analysis/data_layout native/encoding/address_folding native/lowering/control_flow native/analysis/forward_edges native/encoding/instructions native/frame/epilogue native/encoding/scalar_memory native/encoding/strlen native/encoding/zeroing native/encoding/integers native/object/fixups native/object/string_table native/driver/stats_report
FRONTEND_SOURCE_IDS_CPPGM_REPORT_AND_NATIVE_PLANNING := lowir/driver/stats_report native/allocation/movement_stats native/eh/references native/eh/lsda lowir/model/identity native/allocation/spill_slots native/frame/layout native/frame/home_planning native/encoding/globals native/allocation/location_planning
FRONTEND_SOURCE_IDS_CPPGM_LOWIR_CLEANUP := lowir/optimize/cleanup_o1 lowir/optimize/slot_forward_o1 lowir/optimize/slot_promotion lowir/optimize/scalar_rules lowir/optimize/staged_copy_forwarding lowir/optimize/small_object_promotion lowir/optimize/unreachable
FRONTEND_SOURCE_IDS_CPPGM_FRONTEND_LATE := semantic/declarations/entity_ownership lowering/transforms/force_inline lowering/presentation/local_names lowering/core/reachability semantic/analysis/switch
FRONTEND_SOURCE_IDS_CPPGM_LOWIR_ADVANCED := lowir/analysis/function_reachability lowir/analysis/function lowir/analysis/eh_context lowir/optimize/full_unroll_o3 lowir/optimize/private_table_prefilter lowir/optimize/interprocedural_specialization lowir/optimize/copy_elision lowir/optimize/loops lowir/optimize/loop_simplify lowir/optimize/boolean_cfg lowir/optimize/memory_gvn lowir/optimize/expression_key lowir/optimize/pre lowir/analysis/phi_edges native/lowering/phi
FRONTEND_SOURCE_IDS_CPPGM_LOWIR_QUERY_SPLIT := lowir/optimize/terminal_query_split
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_EXTENSION := semantic/lifetime/lifetime semantic/templates/internal_identity semantic/templates/partial_storage semantic/constants/static_storage lowering/constants/templates semantic/object_model/zero_offset_layout semantic/extensions/gnu_asm semantic/extensions/numeric_types semantic/extensions/numeric semantic/extensions/numeric_templates semantic/extensions/complex semantic/extensions/pack_builtins semantic/initialization/aggregates semantic/extensions/compiler_builtins semantic/extensions/control_flow semantic/constants/wide_integer semantic/presentation/source_identity
FRONTEND_SOURCE_IDS_CPPGM_LOWERING_SUPPORT := lowering/objects/cleanup_continuations lowering/objects/zero_initialization
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_FINAL := semantic/templates/shape semantic/expressions/conditions semantic/model/name_identity semantic/presentation/type_view semantic/presentation/type_projection semantic/declarations/anonymous_unions semantic/object_model/class_layout semantic/declarations/class_scope semantic/lifetime/constructor_demand semantic/lifetime/demand semantic/lifetime/demand_stats
FRONTEND_SOURCE_IDS_CPPGM_SYNTAX_FINAL := syntax/model/tags
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_ENUM := semantic/declarations/enums
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_VOCABULARY := semantic/analysis/vocabulary
FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_LAMBDA_PRESENTATION := semantic/presentation/lambdas
FRONTEND_SOURCE_IDS_CPPGM_LOWIR_DEBUG := lowir/io/line_table_debug

FRONTEND_SOURCE_IDS_LOWIR_CORE := lowir/model/identity lowir/io/parse lowir/io/prepare
FRONTEND_SOURCE_IDS_LOWIR_OPT_PRIMARY := $(FRONTEND_SOURCE_IDS_LOWIR_CORE) lowir/io/serialize lowir/analysis/function_reachability lowir/analysis/inline lowir/optimize/inline_o1 lowir/optimize/pipeline
FRONTEND_SOURCE_IDS_LOWIR_OPT_ADVANCED := lowir/driver/stats_report lowir/analysis/function lowir/analysis/eh_context lowir/optimize/full_unroll_o3 lowir/optimize/private_table_prefilter lowir/optimize/interprocedural_specialization lowir/optimize/copy_elision lowir/optimize/loops lowir/optimize/loop_simplify lowir/optimize/boolean_cfg lowir/optimize/memory_gvn lowir/optimize/expression_key lowir/optimize/pre lowir/optimize/cleanup_o1 lowir/optimize/slot_forward_o1 lowir/optimize/slot_promotion lowir/optimize/scalar_rules lowir/optimize/staged_copy_forwarding lowir/optimize/small_object_promotion lowir/optimize/unreachable lowir/analysis/phi_edges

FRONTEND_SOURCE_IDS_NATIVE_PRIMARY := $(FRONTEND_SOURCE_IDS_LOWIR_CORE) lowir/analysis/function_reachability lowir/optimize/force_inline native/errors native/mir/model native/lowering/abi native/analysis/function native/mir/block_labels native/object/code_buffer native/eh/lowering native/allocation/frame_forwarding native/eh/host_regions native/mir/construction native/object/elf_format native/mir/optimize native/driver/program native/allocation/registers native/lowering/selection native/driver/session native/frame/stack native/lowering/varargs native/lowering/wide native/lowering/function native/object/elf_writer
FRONTEND_SOURCE_IDS_NATIVE_EXTENSION := native/driver/stats_report native/allocation/movement_stats native/analysis/data_layout native/encoding/address_folding native/lowering/control_flow native/analysis/forward_edges native/encoding/instructions native/frame/epilogue native/encoding/scalar_memory native/encoding/strlen native/encoding/zeroing native/encoding/integers native/object/fixups native/object/string_table native/eh/references native/eh/lsda native/allocation/spill_slots native/frame/layout native/frame/home_planning native/encoding/globals native/allocation/location_planning lowir/analysis/phi_edges native/lowering/phi

FRONTEND_OBJ_BASENAMES_abimangle := $(FRONTEND_SOURCE_IDS_ABI_MANGLE_TOOL)
FRONTEND_OBJ_BASENAMES_pptoken := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOKEN)
FRONTEND_OBJ_BASENAMES_posttoken := $(FRONTEND_SOURCE_IDS_PREPROCESS_POSTTOKEN)
FRONTEND_OBJ_BASENAMES_ctrlexpr := $(FRONTEND_SOURCE_IDS_PREPROCESS_CONTROL)
FRONTEND_OBJ_BASENAMES_macro := $(FRONTEND_SOURCE_IDS_PREPROCESS_MACRO)
FRONTEND_OBJ_BASENAMES_preproc := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOOL)
FRONTEND_OBJ_BASENAMES_recog := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOOL) $(FRONTEND_SOURCE_IDS_RECOGNITION)
FRONTEND_OBJ_BASENAMES_nsdecl := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOOL) $(FRONTEND_SOURCE_IDS_NAMESPACE_SEMANTIC)
FRONTEND_OBJ_BASENAMES_nsinit := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOOL) $(FRONTEND_SOURCE_IDS_NAMESPACE_INITIALIZATION)
FRONTEND_OBJ_BASENAMES_cy86 := $(FRONTEND_SOURCE_IDS_PREPROCESS_TOOL) $(FRONTEND_SOURCE_IDS_CY86)
FRONTEND_OBJ_BASENAMES_cppgm++ := $(FRONTEND_SOURCE_IDS_CPPGM_PREPROCESS) $(FRONTEND_SOURCE_IDS_CPPGM_SYNTAX_PRIMARY) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_PRIMARY) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_ENUM) $(FRONTEND_SOURCE_IDS_CPPGM_ABI) $(FRONTEND_SOURCE_IDS_CPPGM_LOWERING_PRIMARY_BEFORE_OVERLOAD) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_OVERLOAD) $(FRONTEND_SOURCE_IDS_CPPGM_LOWERING_PRIMARY_AFTER_OVERLOAD) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_NATIVE_PRIMARY) $(FRONTEND_SOURCE_IDS_CPPGM_NATIVE_EXTENSION) $(FRONTEND_SOURCE_IDS_CPPGM_REPORT_AND_NATIVE_PLANNING) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_CLEANUP) $(FRONTEND_SOURCE_IDS_CPPGM_FRONTEND_LATE) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_ADVANCED) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_EXTENSION) $(FRONTEND_SOURCE_IDS_CPPGM_LOWERING_SUPPORT) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_FINAL) $(FRONTEND_SOURCE_IDS_CPPGM_SYNTAX_FINAL) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_VOCABULARY) $(FRONTEND_SOURCE_IDS_CPPGM_SEMANTIC_LAMBDA_PRESENTATION) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_DEBUG) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_QUERY_SPLIT)
FRONTEND_OBJ_BASENAMES_lowiropt := $(FRONTEND_SOURCE_IDS_LOWIR_OPT_PRIMARY) $(FRONTEND_SOURCE_IDS_LOWIR_OPT_ADVANCED) $(FRONTEND_SOURCE_IDS_CPPGM_LOWIR_QUERY_SPLIT)
FRONTEND_OBJ_BASENAMES_lowir2cy86 := $(FRONTEND_SOURCE_IDS_LOWIR_CORE) lowir/cy86/converter
FRONTEND_OBJ_BASENAMES_lowir2native := $(FRONTEND_SOURCE_IDS_NATIVE_PRIMARY) $(FRONTEND_SOURCE_IDS_NATIVE_EXTENSION)
