# Per-tool implementation source lists for the compiler.
#
# Add dev/src/foo.cpp to the responsibility list that owns it. For
# subdirectories, use the path without `.cpp`, such as `syntax/parser/foo`.
# Keep the composed target order stable: it is also the canonical link order.

FRONTEND_SOURCE_SET_TARGETS := abimangle pptoken posttoken ctrlexpr macro preproc recog nsdecl nsinit cy86 cppgm++ lowiropt lowir2cy86 lowir2native
FRONTEND_TEST_RUNNER_SOURCE_ID := support/testing/test_runner
FRONTEND_BUILTIN_CONFIG_SOURCE_ID := preprocess/preprocessor

PREPROCESS_TOKEN_SOURCES := preprocess/tokens/pp_tokenizer
PREPROCESS_POSTTOKEN_SOURCES := $(PREPROCESS_TOKEN_SOURCES) preprocess/tokens/post_tokenizer
PREPROCESS_CONTROL_SOURCES := $(PREPROCESS_POSTTOKEN_SOURCES) preprocess/expressions/control_expression
PREPROCESS_MACRO_SOURCES := $(PREPROCESS_CONTROL_SOURCES) preprocess/hosted/builtin_registry preprocess/hosted/preprocessor_probes preprocess/macros/macro_operator_code preprocess/macros/macro_processor

ABI_MANGLE_TOOL_SOURCES := abi/itanium/abi_mangle_model abi/itanium/abi_mangle_parse abi/itanium/abi_mangle_identity abi/itanium/abi_mangle_graph_argument abi/itanium/abi_mangle_graph_type abi/itanium/abi_mangle_type_vocabulary abi/itanium/abi_mangle_presentation abi/itanium/abi_mangle_substitution abi/itanium/abi_mangle

RECOGNITION_SOURCES := pa6_recognizer
NAMESPACE_SEMANTIC_SOURCES := pa7_semantic
NAMESPACE_INITIALIZATION_SOURCES := pa8_model pa8_parser pa8_semantic
CY86_SOURCES := cy86/cy86_frontend cy86/cy86_backend cy86/cy86_program

CPPGM_PREPROCESS_SOURCES := preprocess/tokens/pp_tokenizer preprocess/tokens/post_tokenizer preprocess/expressions/control_expression preprocess/hosted/preprocessor_probes preprocess/macros/macro_operator_code preprocess/macros/macro_processor preprocess/preprocessor support/interning/frontend_intern preprocess/hosted/builtin_registry hosted_extension_registry
CPPGM_SYNTAX_PRIMARY_SOURCES := pa10_syntax_model pa10_brace_matching pa32_object_attribute_syntax pa10_syntax pa10_syntax_driver pa10_syntax_stats
CPPGM_SEMANTIC_PRIMARY_SOURCES := pa11_model pa11_type_layout pa11_inheritance_model hosted_extension_semantic pa12_semantic pa12_semantic_names pa12_semantic_capacity pa12_semantic_driver pa12_semantic_calls pa12_semantic_constructor_elision pa12_semantic_declarations pa32_object_data_semantic pa33_abi_tag_semantic pa32_template_preemption_semantic pa12_semantic_declarator_types hosted_builtin_semantic pa34_hosted_trait_semantic pa12_semantic_conversion_functions pa12_semantic_function_declarations pa12_semantic_inheritance pa12_semantic_initialization pa12_semantic_list_initialization pa12_semantic_literals pa12_semantic_operators pa12_semantic_render pa12_semantic_scope pa12_semantic_special_members pa12_semantic_storage pa12_semantic_tables pa30_region_semantic pa28_virtual_base_model pa28_virtual_base_semantic pa28_polymorphism_semantic pa25_lambda_capture_semantic pa25_range_for_semantic pa26_exception_semantic pa26_initializer_list_semantic pa26_rtti_semantic pa27_base_path_model pa27_multibase_semantic pa27_member_pointer_semantic pa19_template_syntax_identity pa19_template_presentation pa19_template_semantic pa19_template_validation pa19_function_template_deduction pa19_function_template_instantiation pa19_semantic_ambiguity pa20_constant_semantic pa20_template_semantic pa20_pack_semantic pa21_constant_evaluator pa21_object_evaluator pa21_address_evaluator pa21_local_static_semantic pa22_template_semantic pa22_friend_semantic pa23_nondeduced_semantic pa23_result_identity pa32_function_template_abi_result pa23_placeholder_semantic pa24_template_integration pa17_constructor_definition_semantic pa18_polymorphism_semantic
CPPGM_ABI_SOURCES := abi/itanium/abi_mangle_model abi/itanium/abi_mangle_identity abi/itanium/abi_mangle_graph_argument abi/itanium/abi_mangle_graph_type abi/itanium/abi_mangle_type_vocabulary abi/itanium/abi_mangle_presentation abi/itanium/abi_mangle_substitution abi/itanium/abi_mangle
CPPGM_LOWERING_PRIMARY_SOURCES := pa15_lowir_model pa15_lowering pa15_lowering_abi pa15_lowering_driver pa15_lowering_support pa15_source_type_lowering pa15_lowir_render pa16_static_initializer_lowering pa16_operator_resolution pa18_polymorphism_lowering pa28_polymorphism_lowering pa30_lowir_adapter pa30_object pa30_elf_object
CPPGM_LOWIR_NATIVE_PRIMARY_SOURCES := lowir_parse lowir_prepare lowir_serialize lowir_inline_analysis lowir_inline_o1 lowir_opt lowir_force_inline lowir_native_abi lowir_native_analysis lowir_native_block_labels lowir_native_code_buffer lowir_native_eh lowir_native_frame_forwarding lowir_native_host_eh lowir_native_mir lowir_native_object_elf lowir_native_opt lowir_native_program lowir_native_registers lowir_native_selection lowir_native_session lowir_native_stack lowir_native_varargs lowir_native_wide lowir_native lowir_native_elf mir_model
CPPGM_NATIVE_EXTENSION_SOURCES := lowir_native_data_layout lowir_native_address_folding lowir_native_control_flow lowir_native_forward_edge_analysis lowir_native_encoding lowir_native_epilogue lowir_native_scalar_memory lowir_native_strlen lowir_native_zero_encoding lowir_native_integer_encoding lowir_native_object_fixups lowir_native_elf_string_table lowir_native_stats_report
CPPGM_REPORT_AND_NATIVE_PLANNING_SOURCES := lowir_driver_stats_report lowir_native_movement_stats lowir_native_eh_references lowir_native_lsda lowir_identity lowir_native_spill_slots lowir_native_frame_layout lowir_native_frame_home_planning lowir_native_global_encoding lowir_native_location_planning
CPPGM_LOWIR_CLEANUP_SOURCES := lowir_cleanup_o1 lowir_slot_forward_o1 lowir_slot_promotion lowir_scalar_rules lowir_staged_copy_forwarding lowir_small_object_promotion lowir_unreachable_opt
CPPGM_FRONTEND_LATE_SOURCES := pa32_entity_ownership_semantic pa15_force_inline pa15_local_presentation pa15_function_reachability pa15_switch_semantic
CPPGM_LOWIR_ADVANCED_SOURCES := lowir_function_reachability lowir_function_analysis lowir_eh_context lowir_full_unroll_o3 lowir_interprocedural_specialization lowir_loop_opt lowir_loop_simplify lowir_boolean_cfg lowir_memory_gvn lowir_expression_key lowir_pre lowir_phi_edges lowir_native_phi_lowering
CPPGM_SEMANTIC_EXTENSION_SOURCES := pa12_semantic_lifetime pa19_internal_identity_semantic pa19_template_partial_storage pa21_static_constant_storage pa21_constant_template_lowering pa34_layout_semantic pa34_gnu_asm_semantic pa34_numeric_type_model pa34_numeric_semantic pa34_numeric_template_semantic pa34_complex_semantic pa34_pack_builtin_semantic pa34_aggregate_semantic pa34_compiler_builtin_semantic pa34_control_flow_semantic pa34_wide_constant_semantic pa34_source_identity
CPPGM_LOWERING_SUPPORT_SOURCES := pa16_cleanup_continuation pa16_zero_initialization
CPPGM_SEMANTIC_FINAL_SOURCES := pa19_template_shape_semantic pa12_condition_semantic pa11_name_identity pa11_mainline_view pa11_mainline_projection pa12_anonymous_union_semantic pa12_semantic_class_layout pa12_semantic_class_scope pa12_semantic_constructor_demand pa12_semantic_demand pa12_semantic_demand_stats
CPPGM_SYNTAX_FINAL_SOURCES := pa10_syntax_tags
CPPGM_SEMANTIC_PRESENTATION_SOURCES := pa12_semantic_declaration_names pa12_semantic_enum_declarations pa12_semantic_vocabulary pa22_lambda_presentation
CPPGM_DEBUG_SOURCES := lowir_line_table_debug

LOWIR_CORE_SOURCES := lowir_identity lowir_parse lowir_prepare
LOWIR_OPT_PRIMARY_SOURCES := $(LOWIR_CORE_SOURCES) lowir_serialize lowir_function_reachability lowir_inline_analysis lowir_inline_o1 lowir_opt
LOWIR_OPT_ADVANCED_SOURCES := lowir_driver_stats_report lowir_function_analysis lowir_eh_context lowir_full_unroll_o3 lowir_interprocedural_specialization lowir_loop_opt lowir_loop_simplify lowir_boolean_cfg lowir_memory_gvn lowir_expression_key lowir_pre lowir_cleanup_o1 lowir_slot_forward_o1 lowir_slot_promotion lowir_scalar_rules lowir_staged_copy_forwarding lowir_small_object_promotion lowir_unreachable_opt lowir_phi_edges

NATIVE_PRIMARY_SOURCES := $(LOWIR_CORE_SOURCES) lowir_function_reachability lowir_force_inline mir_model lowir_native_abi lowir_native_analysis lowir_native_block_labels lowir_native_code_buffer lowir_native_eh lowir_native_frame_forwarding lowir_native_host_eh lowir_native_mir lowir_native_object_elf lowir_native_opt lowir_native_program lowir_native_registers lowir_native_selection lowir_native_session lowir_native_stack lowir_native_varargs lowir_native_wide lowir_native lowir_native_elf
NATIVE_EXTENSION_SOURCES := lowir_native_stats_report lowir_native_movement_stats lowir_native_data_layout lowir_native_address_folding lowir_native_control_flow lowir_native_forward_edge_analysis lowir_native_encoding lowir_native_epilogue lowir_native_scalar_memory lowir_native_strlen lowir_native_zero_encoding lowir_native_integer_encoding lowir_native_object_fixups lowir_native_elf_string_table lowir_native_eh_references lowir_native_lsda lowir_native_spill_slots lowir_native_frame_layout lowir_native_frame_home_planning lowir_native_global_encoding lowir_native_location_planning lowir_phi_edges lowir_native_phi_lowering

FRONTEND_OBJ_BASENAMES_abimangle := $(ABI_MANGLE_TOOL_SOURCES)
FRONTEND_OBJ_BASENAMES_pptoken := $(PREPROCESS_TOKEN_SOURCES)
FRONTEND_OBJ_BASENAMES_posttoken := $(PREPROCESS_POSTTOKEN_SOURCES)
FRONTEND_OBJ_BASENAMES_ctrlexpr := $(PREPROCESS_CONTROL_SOURCES)
FRONTEND_OBJ_BASENAMES_macro := $(PREPROCESS_MACRO_SOURCES)
FRONTEND_OBJ_BASENAMES_preproc := $(PREPROCESS_MACRO_SOURCES)
FRONTEND_OBJ_BASENAMES_recog := $(PREPROCESS_MACRO_SOURCES) $(RECOGNITION_SOURCES)
FRONTEND_OBJ_BASENAMES_nsdecl := $(PREPROCESS_MACRO_SOURCES) $(NAMESPACE_SEMANTIC_SOURCES)
FRONTEND_OBJ_BASENAMES_nsinit := $(PREPROCESS_MACRO_SOURCES) $(NAMESPACE_INITIALIZATION_SOURCES)
FRONTEND_OBJ_BASENAMES_cy86 := $(PREPROCESS_MACRO_SOURCES) $(CY86_SOURCES)
FRONTEND_OBJ_BASENAMES_cppgm++ := $(CPPGM_PREPROCESS_SOURCES) $(CPPGM_SYNTAX_PRIMARY_SOURCES) $(CPPGM_SEMANTIC_PRIMARY_SOURCES) $(CPPGM_ABI_SOURCES) $(CPPGM_LOWERING_PRIMARY_SOURCES) $(CPPGM_LOWIR_NATIVE_PRIMARY_SOURCES) $(CPPGM_NATIVE_EXTENSION_SOURCES) $(CPPGM_REPORT_AND_NATIVE_PLANNING_SOURCES) $(CPPGM_LOWIR_CLEANUP_SOURCES) $(CPPGM_FRONTEND_LATE_SOURCES) $(CPPGM_LOWIR_ADVANCED_SOURCES) $(CPPGM_SEMANTIC_EXTENSION_SOURCES) $(CPPGM_LOWERING_SUPPORT_SOURCES) $(CPPGM_SEMANTIC_FINAL_SOURCES) $(CPPGM_SYNTAX_FINAL_SOURCES) $(CPPGM_SEMANTIC_PRESENTATION_SOURCES) $(CPPGM_DEBUG_SOURCES)
FRONTEND_OBJ_BASENAMES_lowiropt := $(LOWIR_OPT_PRIMARY_SOURCES) $(LOWIR_OPT_ADVANCED_SOURCES)
FRONTEND_OBJ_BASENAMES_lowir2cy86 := $(LOWIR_CORE_SOURCES) lowir_cy86
FRONTEND_OBJ_BASENAMES_lowir2native := $(NATIVE_PRIMARY_SOURCES) $(NATIVE_EXTENSION_SOURCES)
