global @sink : i64 = 0

function @first(%value : i64) -> void [binding=internal, unwind=no] {
  block ^entry:
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    return void
}

function @second(%value : i64) -> void [binding=internal, unwind=no] {
  block ^entry:
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    return void
}

function @third(%value : i64) -> void [binding=internal, unwind=no] {
  block ^entry:
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    return void
}

function @fourth(%value : i64) -> void [binding=internal, unwind=no] {
  block ^entry:
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    return void
}

function @fifth(%value : i64) -> void [binding=internal, unwind=no] {
  block ^entry:
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    store i64 %value, @sink
    return void
}

function @main(%value : i64) -> void [role=entry] {
  block ^entry:
    call void @first(%value)
    call void @second(%value)
    call void @third(%value)
    call void @fourth(%value)
    call void @fifth(%value)
    return void
}
