#pragma once

#include <string>

namespace cppgm
{
namespace hosted_builtin
{

enum TypeTraitKind
{
	TYPE_TRAIT_NONE,
	TYPE_TRAIT_HAS_NOTHROW_COPY,
	TYPE_TRAIT_HAS_TRIVIAL_CONSTRUCTOR,
	TYPE_TRAIT_HAS_VIRTUAL_DESTRUCTOR,
	TYPE_TRAIT_IS_ABSTRACT,
	TYPE_TRAIT_IS_AGGREGATE,
	TYPE_TRAIT_IS_ASSIGNABLE,
	TYPE_TRAIT_IS_BASE_OF,
	TYPE_TRAIT_IS_COMPLETE_OR_UNBOUNDED,
	TYPE_TRAIT_IS_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_CONVERTIBLE,
	TYPE_TRAIT_IS_DESTRUCTIBLE,
	TYPE_TRAIT_IS_EMPTY,
	TYPE_TRAIT_IS_ENUM,
	TYPE_TRAIT_IS_FINAL,
	TYPE_TRAIT_IS_FLOATING_POINT,
	TYPE_TRAIT_IS_FUNCTION,
	TYPE_TRAIT_IS_INTEGRAL,
	TYPE_TRAIT_IS_INVOCABLE,
	TYPE_TRAIT_IS_LITERAL_TYPE,
	TYPE_TRAIT_IS_MEMBER_FUNCTION_POINTER,
	TYPE_TRAIT_IS_MEMBER_OBJECT_POINTER,
	TYPE_TRAIT_IS_MEMBER_POINTER,
	TYPE_TRAIT_IS_NOTHROW_ASSIGNABLE,
	TYPE_TRAIT_IS_NOTHROW_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_NOTHROW_INVOCABLE,
	TYPE_TRAIT_IS_POD,
	TYPE_TRAIT_IS_POINTER,
	TYPE_TRAIT_IS_POLYMORPHIC,
	TYPE_TRAIT_IS_REFERENCE,
	TYPE_TRAIT_IS_SAME,
	TYPE_TRAIT_IS_SCALAR,
	TYPE_TRAIT_IS_SIGNED,
	TYPE_TRAIT_IS_STANDARD_LAYOUT,
	TYPE_TRAIT_IS_TRIVIAL,
	TYPE_TRAIT_IS_TRIVIALLY_ASSIGNABLE,
	TYPE_TRAIT_IS_TRIVIALLY_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_TRIVIALLY_COPYABLE,
	TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE,
	TYPE_TRAIT_REFERENCE_BINDS_TO_TEMPORARY,
	TYPE_TRAIT_REFERENCE_CONSTRUCTS_FROM_TEMPORARY
};

enum TypeTransformKind
{
	TYPE_TRANSFORM_NONE,
	TYPE_TRANSFORM_ADD_LVALUE_REFERENCE,
	TYPE_TRANSFORM_ADD_POINTER,
	TYPE_TRANSFORM_ADD_RVALUE_REFERENCE,
	TYPE_TRANSFORM_DECAY,
	TYPE_TRANSFORM_MAKE_SIGNED,
	TYPE_TRANSFORM_MAKE_UNSIGNED,
	TYPE_TRANSFORM_REMOVE_ALL_EXTENTS,
	TYPE_TRANSFORM_REMOVE_CONST,
	TYPE_TRANSFORM_REMOVE_CV,
	TYPE_TRANSFORM_REMOVE_CVREF,
	TYPE_TRANSFORM_REMOVE_POINTER,
	TYPE_TRANSFORM_REMOVE_REFERENCE,
	TYPE_TRANSFORM_REMOVE_VOLATILE,
	TYPE_TRANSFORM_UNDERLYING_TYPE
};

TypeTraitKind FindTypeTrait(const std::string& spelling);
TypeTransformKind FindTypeTransform(const std::string& spelling);

}
}
