#pragma once

#include <string>

namespace cppgm
{
namespace hosted_builtin
{

enum TypeTraitKind
{
	TYPE_TRAIT_NONE,
	TYPE_TRAIT_HAS_NOTHROW_COPY,
	TYPE_TRAIT_HAS_TRIVIAL_CONSTRUCTOR,
	TYPE_TRAIT_HAS_VIRTUAL_DESTRUCTOR,
	TYPE_TRAIT_IS_ABSTRACT,
	TYPE_TRAIT_IS_AGGREGATE,
	TYPE_TRAIT_IS_ASSIGNABLE,
	TYPE_TRAIT_IS_BASE_OF,
	TYPE_TRAIT_IS_COMPLETE_OR_UNBOUNDED,
	TYPE_TRAIT_IS_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_CONVERTIBLE,
	TYPE_TRAIT_IS_DESTRUCTIBLE,
	TYPE_TRAIT_IS_EMPTY,
	TYPE_TRAIT_IS_ENUM,
	TYPE_TRAIT_IS_FINAL,
	TYPE_TRAIT_IS_FLOATING_POINT,
	TYPE_TRAIT_IS_FUNCTION,
	TYPE_TRAIT_IS_INTEGRAL,
	TYPE_TRAIT_IS_INVOCABLE,
	TYPE_TRAIT_IS_LITERAL_TYPE,
	TYPE_TRAIT_IS_MEMBER_FUNCTION_POINTER,
	TYPE_TRAIT_IS_MEMBER_OBJECT_POINTER,
	TYPE_TRAIT_IS_MEMBER_POINTER,
	TYPE_TRAIT_IS_NOTHROW_ASSIGNABLE,
	TYPE_TRAIT_IS_NOTHROW_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_NOTHROW_INVOCABLE,
	TYPE_TRAIT_IS_POD,
	TYPE_TRAIT_IS_POINTER,
	TYPE_TRAIT_IS_POLYMORPHIC,
	TYPE_TRAIT_IS_REFERENCE,
	TYPE_TRAIT_IS_SAME,
	TYPE_TRAIT_IS_SCALAR,
	TYPE_TRAIT_IS_SIGNED,
	TYPE_TRAIT_IS_STANDARD_LAYOUT,
	TYPE_TRAIT_IS_TRIVIAL,
	TYPE_TRAIT_IS_TRIVIALLY_ASSIGNABLE,
	TYPE_TRAIT_IS_TRIVIALLY_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_TRIVIALLY_COPYABLE,
	TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE,
	TYPE_TRAIT_REFERENCE_BINDS_TO_TEMPORARY,
	TYPE_TRAIT_REFERENCE_CONSTRUCTS_FROM_TEMPORARY
};

enum TypeTransformKind
{
	TYPE_TRANSFORM_NONE,
	TYPE_TRANSFORM_ADD_LVALUE_REFERENCE,
	TYPE_TRANSFORM_ADD_POINTER,
	TYPE_TRANSFORM_ADD_RVALUE_REFERENCE,
	TYPE_TRANSFORM_DECAY,
	TYPE_TRANSFORM_MAKE_SIGNED,
	TYPE_TRANSFORM_MAKE_UNSIGNED,
	TYPE_TRANSFORM_REMOVE_ALL_EXTENTS,
	TYPE_TRANSFORM_REMOVE_CONST,
	TYPE_TRANSFORM_REMOVE_CV,
	TYPE_TRANSFORM_REMOVE_CVREF,
	TYPE_TRANSFORM_REMOVE_POINTER,
	TYPE_TRANSFORM_REMOVE_REFERENCE,
	TYPE_TRANSFORM_REMOVE_VOLATILE,
	TYPE_TRANSFORM_UNDERLYING_TYPE
};

enum IntegerIntrinsicKind
{
	INTEGER_INTRINSIC_NONE,
	INTEGER_INTRINSIC_BSWAP16,
	INTEGER_INTRINSIC_BSWAP32,
	INTEGER_INTRINSIC_BSWAP64,
	INTEGER_INTRINSIC_CLZ,
	INTEGER_INTRINSIC_CLZG,
	INTEGER_INTRINSIC_CLZL,
	INTEGER_INTRINSIC_CLZLL,
	INTEGER_INTRINSIC_CTZ,
	INTEGER_INTRINSIC_CTZL,
	INTEGER_INTRINSIC_CTZLL,
	INTEGER_INTRINSIC_POPCOUNT,
	INTEGER_INTRINSIC_POPCOUNTG,
	INTEGER_INTRINSIC_POPCOUNTL,
	INTEGER_INTRINSIC_POPCOUNTLL,
	INTEGER_INTRINSIC_COUNT
};

enum IntegerIntrinsicOperation
{
	INTEGER_OPERATION_BSWAP,
	INTEGER_OPERATION_CLZ,
	INTEGER_OPERATION_CTZ,
	INTEGER_OPERATION_POPCOUNT
};

enum IntegerIntrinsicArgumentRule
{
	INTEGER_ARGUMENT_UNSIGNED_SHORT,
	INTEGER_ARGUMENT_UNSIGNED_INT,
	INTEGER_ARGUMENT_UNSIGNED_LONG,
	INTEGER_ARGUMENT_UNSIGNED_LONG_LONG,
	INTEGER_ARGUMENT_GENERIC_UNSIGNED
};

struct IntegerIntrinsic
{
	const char* spelling;
	IntegerIntrinsicKind kind;
	IntegerIntrinsicOperation operation;
	IntegerIntrinsicArgumentRule argument_rule;
	unsigned arity;
};

enum MemoryIntrinsicKind
{
	MEMORY_INTRINSIC_NONE,
	MEMORY_INTRINSIC_ASSUME_ALIGNED,
	MEMORY_INTRINSIC_BZERO,
	MEMORY_INTRINSIC_MEMCHR,
	MEMORY_INTRINSIC_MEMCPY,
	MEMORY_INTRINSIC_MEMMOVE,
	MEMORY_INTRINSIC_MEMSET,
	MEMORY_INTRINSIC_PREFETCH,
	MEMORY_INTRINSIC_STRCHR,
	MEMORY_INTRINSIC_STRLEN,
	MEMORY_INTRINSIC_COUNT
};

enum MemoryIntrinsicEffect
{
	MEMORY_EFFECT_READNONE,
	MEMORY_EFFECT_READONLY,
	MEMORY_EFFECT_READWRITE
};

enum MemoryIntrinsicLowering
{
	MEMORY_LOWER_IDENTITY,
	MEMORY_LOWER_NOOP,
	MEMORY_LOWER_EXTERNAL
};

struct MemoryIntrinsic
{
	const char* spelling;
	MemoryIntrinsicKind kind;
	unsigned minimum_arity;
	unsigned maximum_arity;
	MemoryIntrinsicEffect effect;
	MemoryIntrinsicLowering lowering;
};

TypeTraitKind FindTypeTrait(const std::string& spelling);
TypeTransformKind FindTypeTransform(const std::string& spelling);
const IntegerIntrinsic* FindIntegerIntrinsic(const std::string& spelling);
const IntegerIntrinsic& GetIntegerIntrinsic(IntegerIntrinsicKind kind);
const MemoryIntrinsic* FindMemoryIntrinsic(const std::string& spelling);
const MemoryIntrinsic& GetMemoryIntrinsic(MemoryIntrinsicKind kind);

}
}
