#pragma once

#include <cstdint>
#include <string>

namespace cppgm
{
namespace hosted_builtin
{

enum TypeTraitKind
{
	TYPE_TRAIT_NONE,
	TYPE_TRAIT_ARRAY_RANK,
	TYPE_TRAIT_HAS_NOTHROW_COPY,
	TYPE_TRAIT_HAS_TRIVIAL_CONSTRUCTOR,
	TYPE_TRAIT_HAS_VIRTUAL_DESTRUCTOR,
	TYPE_TRAIT_IS_ABSTRACT,
	TYPE_TRAIT_IS_AGGREGATE,
	TYPE_TRAIT_IS_ASSIGNABLE,
	TYPE_TRAIT_IS_BASE_OF,
	TYPE_TRAIT_IS_CLASS,
	TYPE_TRAIT_IS_COMPLETE_OR_UNBOUNDED,
	TYPE_TRAIT_IS_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_CONVERTIBLE,
	TYPE_TRAIT_IS_DESTRUCTIBLE,
	TYPE_TRAIT_IS_EMPTY,
	TYPE_TRAIT_IS_ENUM,
	TYPE_TRAIT_IS_FINAL,
	TYPE_TRAIT_IS_FLOATING_POINT,
	TYPE_TRAIT_IS_FUNCTION,
	TYPE_TRAIT_IS_INTEGRAL,
	TYPE_TRAIT_IS_INVOCABLE,
	TYPE_TRAIT_IS_LITERAL_TYPE,
	TYPE_TRAIT_IS_MEMBER_FUNCTION_POINTER,
	TYPE_TRAIT_IS_MEMBER_OBJECT_POINTER,
	TYPE_TRAIT_IS_MEMBER_POINTER,
	TYPE_TRAIT_IS_NOTHROW_ASSIGNABLE,
	TYPE_TRAIT_IS_NOTHROW_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_NOTHROW_INVOCABLE,
	TYPE_TRAIT_IS_POD,
	TYPE_TRAIT_IS_POINTER,
	TYPE_TRAIT_IS_POLYMORPHIC,
	TYPE_TRAIT_IS_REFERENCE,
	TYPE_TRAIT_IS_SAME,
	TYPE_TRAIT_IS_SCALAR,
	TYPE_TRAIT_IS_SIGNED,
	TYPE_TRAIT_IS_STANDARD_LAYOUT,
	TYPE_TRAIT_IS_TRIVIAL,
	TYPE_TRAIT_IS_TRIVIALLY_ASSIGNABLE,
	TYPE_TRAIT_IS_TRIVIALLY_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_TRIVIALLY_COPYABLE,
	TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE,
	TYPE_TRAIT_IS_UNION,
	TYPE_TRAIT_REFERENCE_BINDS_TO_TEMPORARY,
	TYPE_TRAIT_REFERENCE_CONSTRUCTS_FROM_TEMPORARY
};

enum TypeTransformKind
{
	TYPE_TRANSFORM_NONE,
	TYPE_TRANSFORM_ADD_LVALUE_REFERENCE,
	TYPE_TRANSFORM_ADD_POINTER,
	TYPE_TRANSFORM_ADD_RVALUE_REFERENCE,
	TYPE_TRANSFORM_DECAY,
	TYPE_TRANSFORM_MAKE_SIGNED,
	TYPE_TRANSFORM_MAKE_UNSIGNED,
	TYPE_TRANSFORM_REMOVE_ALL_EXTENTS,
	TYPE_TRANSFORM_REMOVE_CONST,
	TYPE_TRANSFORM_REMOVE_CV,
	TYPE_TRANSFORM_REMOVE_CVREF,
	TYPE_TRANSFORM_REMOVE_POINTER,
	TYPE_TRANSFORM_REMOVE_REFERENCE,
	TYPE_TRANSFORM_REMOVE_VOLATILE,
	TYPE_TRANSFORM_UNDERLYING_TYPE
};

enum IntegerIntrinsicKind : std::uint8_t
{
	INTEGER_INTRINSIC_NONE,
	INTEGER_INTRINSIC_BSWAP16,
	INTEGER_INTRINSIC_BSWAP32,
	INTEGER_INTRINSIC_BSWAP64,
	INTEGER_INTRINSIC_CLZ,
	INTEGER_INTRINSIC_CLZG,
	INTEGER_INTRINSIC_CLZL,
	INTEGER_INTRINSIC_CLZLL,
	INTEGER_INTRINSIC_CTZ,
	INTEGER_INTRINSIC_CTZL,
	INTEGER_INTRINSIC_CTZLL,
	INTEGER_INTRINSIC_POPCOUNT,
	INTEGER_INTRINSIC_POPCOUNTG,
	INTEGER_INTRINSIC_POPCOUNTL,
	INTEGER_INTRINSIC_POPCOUNTLL,
	INTEGER_INTRINSIC_COUNT
};

enum IntegerIntrinsicOperation
{
	INTEGER_OPERATION_BSWAP,
	INTEGER_OPERATION_CLZ,
	INTEGER_OPERATION_CTZ,
	INTEGER_OPERATION_POPCOUNT
};

enum IntegerIntrinsicArgumentRule
{
	INTEGER_ARGUMENT_UNSIGNED_SHORT,
	INTEGER_ARGUMENT_UNSIGNED_INT,
	INTEGER_ARGUMENT_UNSIGNED_LONG,
	INTEGER_ARGUMENT_UNSIGNED_LONG_LONG,
	INTEGER_ARGUMENT_GENERIC_UNSIGNED
};

struct IntegerIntrinsic
{
	const char* spelling;
	IntegerIntrinsicKind kind;
	IntegerIntrinsicOperation operation;
	IntegerIntrinsicArgumentRule argument_rule;
	unsigned arity;
};

enum FloatingIntrinsicKind : std::uint8_t
{
	FLOATING_INTRINSIC_NONE,
	FLOATING_INTRINSIC_CEIL,
	FLOATING_INTRINSIC_CEILF,
	FLOATING_INTRINSIC_CEILL,
	FLOATING_INTRINSIC_FLT_ROUNDS,
	FLOATING_INTRINSIC_FPCLASSIFY,
	FLOATING_INTRINSIC_HUGE_VAL,
	FLOATING_INTRINSIC_HUGE_VALF,
	FLOATING_INTRINSIC_HUGE_VALL,
	FLOATING_INTRINSIC_INF,
	FLOATING_INTRINSIC_INFF,
	FLOATING_INTRINSIC_INFL,
	FLOATING_INTRINSIC_ISFINITE,
	FLOATING_INTRINSIC_ISINF,
	FLOATING_INTRINSIC_ISNAN,
	FLOATING_INTRINSIC_ISNORMAL,
	FLOATING_INTRINSIC_NAN,
	FLOATING_INTRINSIC_NANF,
	FLOATING_INTRINSIC_NANL,
	FLOATING_INTRINSIC_NANS,
	FLOATING_INTRINSIC_NANSF,
	FLOATING_INTRINSIC_NANSL,
	FLOATING_INTRINSIC_SIGNBIT,
	FLOATING_INTRINSIC_COUNT
};

enum FloatingIntrinsicOperation
{
	FLOATING_OPERATION_EXTERNAL_CEIL,
	FLOATING_OPERATION_ROUNDING_MODE,
	FLOATING_OPERATION_CLASSIFY,
	FLOATING_OPERATION_INFINITY,
	FLOATING_OPERATION_ISFINITE,
	FLOATING_OPERATION_ISINF,
	FLOATING_OPERATION_ISNAN,
	FLOATING_OPERATION_ISNORMAL,
	FLOATING_OPERATION_NAN,
	FLOATING_OPERATION_SNAN,
	FLOATING_OPERATION_SIGNBIT
};

enum FloatingIntrinsicFormat
{
	FLOATING_FORMAT_NONE,
	FLOATING_FORMAT_FLOAT,
	FLOATING_FORMAT_DOUBLE,
	FLOATING_FORMAT_LONG_DOUBLE
};

struct FloatingIntrinsic
{
	const char* spelling;
	FloatingIntrinsicKind kind;
	FloatingIntrinsicOperation operation;
	FloatingIntrinsicFormat result_format;
	unsigned arity;
};

enum MemoryIntrinsicKind : std::uint8_t
{
	MEMORY_INTRINSIC_NONE,
	MEMORY_INTRINSIC_ASSUME_ALIGNED,
	MEMORY_INTRINSIC_BZERO,
	MEMORY_INTRINSIC_MEMCHR,
	MEMORY_INTRINSIC_MEMCMP,
	MEMORY_INTRINSIC_MEMCPY,
	MEMORY_INTRINSIC_MEMMOVE,
	MEMORY_INTRINSIC_MEMSET,
	MEMORY_INTRINSIC_PREFETCH,
	MEMORY_INTRINSIC_STRCHR,
	MEMORY_INTRINSIC_STRCMP,
	MEMORY_INTRINSIC_STRLEN,
	MEMORY_INTRINSIC_COUNT
};

enum MemoryIntrinsicEffect
{
	MEMORY_EFFECT_READNONE,
	MEMORY_EFFECT_READONLY,
	MEMORY_EFFECT_READWRITE
};

enum MemoryIntrinsicLowering
{
	MEMORY_LOWER_IDENTITY,
	MEMORY_LOWER_NOOP,
	MEMORY_LOWER_EXTERNAL
};

struct MemoryIntrinsic
{
	const char* spelling;
	MemoryIntrinsicKind kind;
	unsigned minimum_arity;
	unsigned maximum_arity;
	MemoryIntrinsicEffect effect;
	MemoryIntrinsicLowering lowering;
};

enum VectorIntrinsicKind : std::uint8_t
{
	VECTOR_INTRINSIC_NONE,
	VECTOR_INTRINSIC_IA32_VEC_EXT_V2SI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V2SI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V4HI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V8QI,
	VECTOR_INTRINSIC_COUNT
};

enum VectorIntrinsicOperation
{
	VECTOR_OPERATION_INIT,
	VECTOR_OPERATION_EXTRACT
};

enum VectorIntrinsicElement
{
	VECTOR_ELEMENT_I8,
	VECTOR_ELEMENT_I16,
	VECTOR_ELEMENT_I32
};

struct VectorIntrinsic
{
	const char* spelling;
	VectorIntrinsicKind kind;
	VectorIntrinsicOperation operation;
	VectorIntrinsicElement element;
	unsigned lane_count;
};

enum AtomicIntrinsicKind : std::uint8_t
{
	ATOMIC_INTRINSIC_NONE,
	ATOMIC_INTRINSIC_ADD_FETCH,
	ATOMIC_INTRINSIC_ALWAYS_LOCK_FREE,
	ATOMIC_INTRINSIC_CLEAR,
	ATOMIC_INTRINSIC_COMPARE_EXCHANGE_N,
	ATOMIC_INTRINSIC_EXCHANGE_N,
	ATOMIC_INTRINSIC_FETCH_ADD,
	ATOMIC_INTRINSIC_FETCH_AND,
	ATOMIC_INTRINSIC_FETCH_OR,
	ATOMIC_INTRINSIC_FETCH_SUB,
	ATOMIC_INTRINSIC_FETCH_XOR,
	ATOMIC_INTRINSIC_IS_LOCK_FREE,
	ATOMIC_INTRINSIC_LOAD,
	ATOMIC_INTRINSIC_LOAD_N,
	ATOMIC_INTRINSIC_SIGNAL_FENCE,
	ATOMIC_INTRINSIC_STORE,
	ATOMIC_INTRINSIC_STORE_N,
	ATOMIC_INTRINSIC_TEST_AND_SET,
	ATOMIC_INTRINSIC_THREAD_FENCE,
	ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_STRONG,
	ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_WEAK,
	ATOMIC_INTRINSIC_C11_EXCHANGE,
	ATOMIC_INTRINSIC_C11_FETCH_ADD,
	ATOMIC_INTRINSIC_C11_FETCH_AND,
	ATOMIC_INTRINSIC_C11_FETCH_OR,
	ATOMIC_INTRINSIC_C11_FETCH_SUB,
	ATOMIC_INTRINSIC_C11_FETCH_XOR,
	ATOMIC_INTRINSIC_C11_INIT,
	ATOMIC_INTRINSIC_C11_IS_LOCK_FREE,
	ATOMIC_INTRINSIC_C11_LOAD,
	ATOMIC_INTRINSIC_C11_SIGNAL_FENCE,
	ATOMIC_INTRINSIC_C11_STORE,
	ATOMIC_INTRINSIC_C11_THREAD_FENCE,
	ATOMIC_INTRINSIC_SYNC_FETCH_AND_ADD,
	ATOMIC_INTRINSIC_SYNC_LOCK_RELEASE,
	ATOMIC_INTRINSIC_SYNC_LOCK_TEST_AND_SET,
	ATOMIC_INTRINSIC_SYNC_SYNCHRONIZE,
	ATOMIC_INTRINSIC_SYNC_VAL_COMPARE_AND_SWAP,
	ATOMIC_INTRINSIC_COUNT
};

enum AtomicIntrinsicShape
{
	ATOMIC_SHAPE_LOCK_FREE,
	ATOMIC_SHAPE_LOAD,
	ATOMIC_SHAPE_LOAD_OUT,
	ATOMIC_SHAPE_STORE,
	ATOMIC_SHAPE_STORE_FROM,
	ATOMIC_SHAPE_EXCHANGE,
	ATOMIC_SHAPE_COMPARE_EXCHANGE,
	ATOMIC_SHAPE_SYNC_COMPARE_EXCHANGE,
	ATOMIC_SHAPE_FETCH_UPDATE,
	ATOMIC_SHAPE_TEST_AND_SET,
	ATOMIC_SHAPE_CLEAR,
	ATOMIC_SHAPE_FENCE
};

enum AtomicUpdateOperation
{
	ATOMIC_UPDATE_NONE,
	ATOMIC_UPDATE_ADD,
	ATOMIC_UPDATE_SUB,
	ATOMIC_UPDATE_AND,
	ATOMIC_UPDATE_OR,
	ATOMIC_UPDATE_XOR
};

struct AtomicIntrinsic
{
	const char* spelling;
	AtomicIntrinsicKind kind;
	AtomicIntrinsicShape shape;
	AtomicUpdateOperation update;
	unsigned arity;
	bool result_is_new;
	bool requires_atomic_pointee;
};

TypeTraitKind FindTypeTrait(const std::string& spelling);
TypeTransformKind FindTypeTransform(const std::string& spelling);
const IntegerIntrinsic* FindIntegerIntrinsic(const std::string& spelling);
const IntegerIntrinsic& GetIntegerIntrinsic(IntegerIntrinsicKind kind);
const FloatingIntrinsic* FindFloatingIntrinsic(const std::string& spelling);
const FloatingIntrinsic& GetFloatingIntrinsic(FloatingIntrinsicKind kind);
const MemoryIntrinsic* FindMemoryIntrinsic(const std::string& spelling);
const MemoryIntrinsic& GetMemoryIntrinsic(MemoryIntrinsicKind kind);
const VectorIntrinsic* FindVectorIntrinsic(const std::string& spelling);
const VectorIntrinsic& GetVectorIntrinsic(VectorIntrinsicKind kind);
const AtomicIntrinsic* FindAtomicIntrinsic(const std::string& spelling);
const AtomicIntrinsic& GetAtomicIntrinsic(AtomicIntrinsicKind kind);

}
}
