#ifndef CPPGM_SYNTAX_MODEL_TAG_CATALOG_H
#define CPPGM_SYNTAX_MODEL_TAG_CATALOG_H

#define CPPGM_FOR_EACH_SYNTAX_TAG(APPLY) \
	APPLY(STAG_ABSTRACT_DECLARATOR, "abstract-declarator") \
	APPLY(STAG_ACCESS_SPECIFIER, "access-specifier") \
	APPLY(STAG_ALIAS_DECLARATION, "alias-declaration") \
	APPLY(STAG_ALIGNMENT_SPECIFIER, "alignment-specifier") \
	APPLY(STAG_ARGUMENT_LIST, "argument-list") \
	APPLY(STAG_ARRAY_DELETE, "array-delete") \
	APPLY(STAG_ARRAY_SUFFIX, "array-suffix") \
	APPLY(STAG_ASSIGNMENT_EXPRESSION, "assignment-expression") \
	APPLY(STAG_ATOMIC_TYPE_SPECIFIER, "atomic-type-specifier") \
	APPLY(STAG_BASE_NAME, "base-name") \
	APPLY(STAG_BASE_SPECIFIER, "base-specifier") \
	APPLY(STAG_BINARY_EXPRESSION, "binary-expression") \
	APPLY(STAG_BINDING_IDENTIFIER, "binding-identifier") \
	APPLY(STAG_BIT_FIELD_DECLARATION, "bit-field-declaration") \
	APPLY(STAG_BIT_FIELD_DECLARATOR, "bit-field-declarator") \
	APPLY(STAG_BITINT_TYPE_SPECIFIER, "bitint-type-specifier") \
	APPLY(STAG_BRACED_INIT_LIST, "braced-init-list") \
	APPLY(STAG_BREAK_STATEMENT, "break-statement") \
	APPLY(STAG_BUILTIN_OFFSETOF_EXPRESSION, "builtin-offsetof-expression") \
	APPLY(STAG_BUILTIN_TRANSFORM_TYPE, "builtin-transform-type") \
	APPLY(STAG_BUILTIN_TYPE_OPERAND, "builtin-type-operand") \
	APPLY(STAG_BUILTIN_TYPE_TRAIT_EXPRESSION, "builtin-type-trait-expression") \
	APPLY(STAG_CALL_EXPRESSION, "call-expression") \
	APPLY(STAG_CASE_STATEMENT, "case-statement") \
	APPLY(STAG_CAST_EXPRESSION, "cast-expression") \
	APPLY(STAG_CLASS_FORWARD_DECLARATION, "class-forward-declaration") \
	APPLY(STAG_CLASS_SPECIFIER, "class-specifier") \
	APPLY(STAG_COMPOUND_STATEMENT, "compound-statement") \
	APPLY(STAG_CONDITION, "condition") \
	APPLY(STAG_CONDITION_DECLARATION, "condition-declaration") \
	APPLY(STAG_CONDITIONAL_EXPRESSION, "conditional-expression") \
	APPLY(STAG_CONTINUE_STATEMENT, "continue-statement") \
	APPLY(STAG_CV_QUALIFIER, "cv-qualifier") \
	APPLY(STAG_DECL_SPECIFIER, "decl-specifier") \
	APPLY(STAG_DECL_SPECIFIER_SEQ, "decl-specifier-seq") \
	APPLY(STAG_DECLARATOR, "declarator") \
	APPLY(STAG_DECLTYPE_SPECIFIER, "decltype-specifier") \
	APPLY(STAG_DEDUCTION_GUIDE_DECLARATION, "deduction-guide-declaration") \
	APPLY(STAG_DEFAULT_STATEMENT, "default-statement") \
	APPLY(STAG_DEFAULT_TEMPLATE_ARGUMENT, "default-template-argument") \
	APPLY(STAG_DELETE_EXPRESSION, "delete-expression") \
	APPLY(STAG_DESIGNATED_INITIALIZER, "designated-initializer") \
	APPLY(STAG_DO_STATEMENT, "do-statement") \
	APPLY(STAG_ELSE, "else") \
	APPLY(STAG_EMPTY_DECLARATION, "empty-declaration") \
	APPLY(STAG_ENUM_SPECIFIER, "enum-specifier") \
	APPLY(STAG_ENUMERATOR, "enumerator") \
	APPLY(STAG_EXCEPTION_DECLARATION, "exception-declaration") \
	APPLY(STAG_EXPLICIT_INSTANTIATION_DECLARATION, "explicit-instantiation-declaration") \
	APPLY(STAG_EXPLICIT_INSTANTIATION_DEFINITION, "explicit-instantiation-definition") \
	APPLY(STAG_EXPRESSION_STATEMENT, "expression-statement") \
	APPLY(STAG_FOLD_BINARY, "fold-binary") \
	APPLY(STAG_FOLD_EXPRESSION, "fold-expression") \
	APPLY(STAG_FOLD_LEFT, "fold-left") \
	APPLY(STAG_FOLD_RIGHT, "fold-right") \
	APPLY(STAG_FOR_INIT_STATEMENT, "for-init-statement") \
	APPLY(STAG_FOR_STATEMENT, "for-statement") \
	APPLY(STAG_FUNCTION_DEFINITION, "function-definition") \
	APPLY(STAG_GLOBAL_QUALIFIER, "global-qualifier") \
	APPLY(STAG_GLOBAL_SCOPE, "global-scope") \
	APPLY(STAG_GNU_ASM_CLOBBER, "gnu-asm-clobber") \
	APPLY(STAG_GNU_ASM_GOTO_LABEL, "gnu-asm-goto-label") \
	APPLY(STAG_GNU_ASM_INPUT, "gnu-asm-input") \
	APPLY(STAG_GNU_ASM_OUTPUT, "gnu-asm-output") \
	APPLY(STAG_GNU_ASM_STATEMENT, "gnu-asm-statement") \
	APPLY(STAG_GNU_ASM_SYMBOL, "gnu-asm-symbol") \
	APPLY(STAG_GNU_ATTRIBUTE, "gnu-attribute") \
	APPLY(STAG_GNU_ATTRIBUTE_ARGUMENT, "gnu-attribute-argument") \
	APPLY(STAG_GNU_ATTRIBUTE_NONLITERAL_ARGUMENT, "gnu-attribute-nonliteral-argument") \
	APPLY(STAG_GOTO_STATEMENT, "goto-statement") \
	APPLY(STAG_HANDLER, "handler") \
	APPLY(STAG_ID_EXPRESSION, "id-expression") \
	APPLY(STAG_IDENTIFIER, "identifier") \
	APPLY(STAG_IF_STATEMENT, "if-statement") \
	APPLY(STAG_INIT_DECLARATOR_LIST, "init-declarator-list") \
	APPLY(STAG_INITIALIZER, "initializer") \
	APPLY(STAG_ITERATION, "iteration") \
	APPLY(STAG_KEYWORD_LITERAL, "keyword-literal") \
	APPLY(STAG_LABELED_STATEMENT, "labeled-statement") \
	APPLY(STAG_LAMBDA_CAPTURE_COPY, "lambda-capture-copy") \
	APPLY(STAG_LAMBDA_CAPTURE_COPY_PACK, "lambda-capture-copy-pack") \
	APPLY(STAG_LAMBDA_CAPTURE_THIS, "lambda-capture-this") \
	APPLY(STAG_LAMBDA_DECLARATOR, "lambda-declarator") \
	APPLY(STAG_LAMBDA_EXPRESSION, "lambda-expression") \
	APPLY(STAG_LAMBDA_INTRODUCER, "lambda-introducer") \
	APPLY(STAG_LAYOUT_PACK_POP, "layout-pack-pop") \
	APPLY(STAG_LAYOUT_PACK_PUSH, "layout-pack-push") \
	APPLY(STAG_LINKAGE_SPECIFICATION, "linkage-specification") \
	APPLY(STAG_LITERAL, "literal") \
	APPLY(STAG_MEM_INITIALIZER, "mem-initializer") \
	APPLY(STAG_MEMBER_EXPRESSION, "member-expression") \
	APPLY(STAG_NAME_COMPONENT, "name-component") \
	APPLY(STAG_NAMESPACE_ALIAS_DEFINITION, "namespace-alias-definition") \
	APPLY(STAG_NAMESPACE_DEFINITION, "namespace-definition") \
	APPLY(STAG_NESTED_DECLARATOR, "nested-declarator") \
	APPLY(STAG_NEW_EXPRESSION, "new-expression") \
	APPLY(STAG_NON_TYPE_TEMPLATE_PARAMETER, "non-type-template-parameter") \
	APPLY(STAG_PACK_EXPANSION, "pack-expansion") \
	APPLY(STAG_PACK_EXPANSION_EXPRESSION, "pack-expansion-expression") \
	APPLY(STAG_PARAMETER_CLAUSE, "parameter-clause") \
	APPLY(STAG_PARAMETER_DECLARATION, "parameter-declaration") \
	APPLY(STAG_PARAMETER_PACK, "parameter-pack") \
	APPLY(STAG_PAREN_ARGUMENT_LIST, "paren-argument-list") \
	APPLY(STAG_PAREN_INITIALIZER, "paren-initializer") \
	APPLY(STAG_PARENTHESIZED_EXPRESSION, "parenthesized-expression") \
	APPLY(STAG_POSTFIX_EXPRESSION, "postfix-expression") \
	APPLY(STAG_PTR_OPERATOR, "ptr-operator") \
	APPLY(STAG_RANGE_DECLARATION, "range-declaration") \
	APPLY(STAG_RANGE_FOR_STATEMENT, "range-for-statement") \
	APPLY(STAG_RANGE_INITIALIZER, "range-initializer") \
	APPLY(STAG_REF_QUALIFIER, "ref-qualifier") \
	APPLY(STAG_RETURN_STATEMENT, "return-statement") \
	APPLY(STAG_SIMPLE_DECLARATION, "simple-declaration") \
	APPLY(STAG_SIZEOF_EXPRESSION, "sizeof-expression") \
	APPLY(STAG_SIZEOF_PACK_EXPRESSION, "sizeof-pack-expression") \
	APPLY(STAG_SPECIAL_MEMBER_DECLARATION, "special-member-declaration") \
	APPLY(STAG_SPECIAL_MEMBER_DEFINITION, "special-member-definition") \
	APPLY(STAG_STANDARD_ATTRIBUTE, "standard-attribute") \
	APPLY(STAG_STATEMENT_EXPRESSION, "statement-expression") \
	APPLY(STAG_STATIC_ASSERT_DECLARATION, "static-assert-declaration") \
	APPLY(STAG_STRUCTURED_BINDING, "structured-binding") \
	APPLY(STAG_STRUCTURED_TYPE_NAME, "structured-type-name") \
	APPLY(STAG_SUBSCRIPT_EXPRESSION, "subscript-expression") \
	APPLY(STAG_SWITCH_STATEMENT, "switch-statement") \
	APPLY(STAG_TARGET, "target") \
	APPLY(STAG_TEMPLATE_DECLARATION, "template-declaration") \
	APPLY(STAG_TEMPLATE_PARAMETER_CLAUSE, "template-parameter-clause") \
	APPLY(STAG_THEN, "then") \
	APPLY(STAG_THROW_EXPRESSION, "throw-expression") \
	APPLY(STAG_THROW_STATEMENT, "throw-statement") \
	APPLY(STAG_TRY_BLOCK, "try-block") \
	APPLY(STAG_TYPE_ID, "type-id") \
	APPLY(STAG_TYPE_NAME, "type-name") \
	APPLY(STAG_TYPE_PARAMETER, "type-parameter") \
	APPLY(STAG_TYPE_SPECIFIER, "type-specifier") \
	APPLY(STAG_TYPE_SPECIFIER_SEQ, "type-specifier-seq") \
	APPLY(STAG_TYPE_TRAIT_EXPRESSION, "type-trait-expression") \
	APPLY(STAG_UNARY_EXPRESSION, "unary-expression") \
	APPLY(STAG_USING_DECLARATION, "using-declaration") \
	APPLY(STAG_USING_DIRECTIVE, "using-directive") \
	APPLY(STAG_VIRT_SPECIFIER, "virt-specifier") \
	APPLY(STAG_BASE_CLAUSE, "base-clause") \
	APPLY(STAG_CLASS_KEY, "class-key") \
	APPLY(STAG_CLASS_VIRT_SPECIFIER, "class-virt-specifier") \
	APPLY(STAG_CONSTEXPR_SELECTION, "constexpr-selection") \
	APPLY(STAG_CONVERSION_TYPE_ID, "conversion-type-id") \
	APPLY(STAG_CTOR_INITIALIZER, "ctor-initializer") \
	APPLY(STAG_DECLTYPE_NAME, "decltype-name") \
	APPLY(STAG_DEFAULT_ARGUMENT, "default-argument") \
	APPLY(STAG_ELLIPSIS, "ellipsis") \
	APPLY(STAG_ENUM_KEY, "enum-key") \
	APPLY(STAG_EXCEPTION_TYPE_LIST, "exception-type-list") \
	APPLY(STAG_FUNCTION_QUALIFIER, "function-qualifier") \
	APPLY(STAG_FUNCTION_TRY_BLOCK, "function-try-block") \
	APPLY(STAG_GNU_ASM_LABEL, "gnu-asm-label") \
	APPLY(STAG_INLINE, "inline") \
	APPLY(STAG_LAMBDA_SPECIFIER, "lambda-specifier") \
	APPLY(STAG_MEM_INITIALIZER_ID, "mem-initializer-id") \
	APPLY(STAG_MEMBER_SPECIFIERS, "member-specifiers") \
	APPLY(STAG_NOEXCEPT_SPECIFICATION, "noexcept-specification") \
	APPLY(STAG_PLACEMENT, "placement") \
	APPLY(STAG_QUALIFIED_NAME, "qualified-name") \
	APPLY(STAG_QUALIFIED_TYPE_NAME, "qualified-type-name") \
	APPLY(STAG_SELECTION_INIT_STATEMENT, "selection-init-statement") \
	APPLY(STAG_SPECIAL_INITIALIZER, "special-initializer") \
	APPLY(STAG_TEMPLATE_PARAMETER_LIST, "template-parameter-list") \
	APPLY(STAG_TEMPLATE_TEMPLATE_PARAMETER, "template-template-parameter") \
	APPLY(STAG_TEMPLATE_TYPE_ARGUMENT_LIST, "template-type-argument-list") \
	APPLY(STAG_TRAILING_RETURN_TYPE, "trailing-return-type") \
	APPLY(STAG_TYPE_PACK_EXPANSION, "type-pack-expansion") \
	APPLY(STAG_VIRTUAL, "virtual") \
	APPLY(STAG_WHILE_STATEMENT, "while-statement") \
	/**/

#endif
